Add run-test-apic_x86-intdbg target.
This does not use kvm to run the test, but instead uses the "default"
cpu and passes the '-d int' parameter to qemu-system_x86_64.runner.sh.
The '-d int' causes qemu-system-x86_64 to output interrupt debug
information. I got the '-d int' trick from Phillpp Oppermann
see (this)[http://os.phil-opp.com/set-up-rust.html].

Below we the first interrupt, '  0: v=08 ....' is the double fault
interrupt and it took 17M loops before the double fault occurred. Then
we see three more faults which are the three faults caused by reset_x86.

So we see the same "double fault" on qemu in two configurations, kvm
and non-kvm, as well as on real hardware, so this isn't a fluke.
Phillipp Oppermann (suggests)[http://os.phil-opp.com/entering-longmode.html#comment-2546195102]
that the problem might be the (PIC)[http://wiki.osdev.org/Programmable_Interval_Timer].

  Booting `test_apic_x86'

ac_init addr=0000000000102440
mb_info: 0x0000000000222f10
 total_size=1664
 reserved=0x0
 mb_end=0x0000000000223590
type=1 size=22
 cmd_line=test_apic_x86
type=2 size=24
type=10 size=28
type=6 size=160
 memory map:
  entry_size=24
  entry_version=0
  0: base_addr=0x0000000000000000 length=0x9fc00 type=1 reserved=0
  1: base_addr=0x000000000009fc00 length=0x400 type=2 reserved=0
  2: base_addr=0x00000000000f0000 length=0x10000 type=2 reserved=0
  3: base_addr=0x0000000000100000 length=0x7ee0000 type=1 reserved=0
  4: base_addr=0x0000000007fe0000 length=0x20000 type=2 reserved=0
  5: base_addr=0x00000000fffc0000 length=0x40000 type=2 reserved=0
total_length=133692416(0x7f7fc00)
init_page_tables:+
RAM: base_addr=0x0 length=0x9fc00 type=1 reserved=0
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=159
RAM: base_addr=0x100000 length=0x7ee0000 type=1 reserved=0
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=62 4k=736
RAM: total_length=133692416(0x7f7fc00)
CR3 is now 0x209000
init_page_tables:- Changed to our page tables, CR3=0x107000
type=9 size=1300
type=4 size=16
 basic memory info:
  mem_lower=639k
  mem_upper=129920k
type=5 size=20
type=8 size=32
type=14 size=28
APIC present
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=1
msr_apic_base 0x1b: 0xfee00900
 reserved_0=0
 bsp=1
 reserved_1=0
 extd=0
 e=1
 base=0xfee00000
 phy_addr=0xfee00000
 lin_addr=0xfee00000
 local_id=0x0
test_apic_version
msr_apic_base 0x1b: 0xfee00900
 reserved_0=0
 bsp=1
 reserved_1=0
 extd=0
 e=1
 base=0xfee00000
ver_reg=0x00000000fee00030
*ver_reg=0x50014
test_apic_timer
test_apic_timer: lvtu.raw=0x10000
test_apic_timer: lvtu.fields.vector=0
test_apic_timer: lvtu.fields.status=0
test_apic_timer: lvtu.fields.disable=1
test_apic_timer: lvtu.fields.mode=0
test_apic_timer: lvtu2.raw=0x50
test_apic_timer: lvtu2.fields.vector=80
test_apic_timer: lvtu2fields.status=0
test_apic_timer: lvtu2.fields.disable=0
test_apic_timer: lvtu2.fields.mode=0
test_apic_timer: sti divisor=6 apic_timer_initial_count=0
     0: v=08 e=0000 i=0 cpl=0 IP=0008:0000000000100618 pc=0000000000100618 SP=0010:000000000020dfa8 env->regs[R_EAX]=000000003a91af5f
RAX=000000003a91af5f RBX=00000000fee00b00 RCX=0000000000000000 RDX=0000000001091aa1
RSI=0000000000000000 RDI=000000000000000a RBP=0000000000000000 RSP=000000000020dfa8
R8 =000000000000000a R9 =0000000000000000 R10=0000000000000000 R11=000000000000001b
R12=0000000000000000 R13=0000000000010000 R14=0000000000000000 R15=0000000000000000
RIP=0000000000100618 RFL=00200216 [----AP-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
DS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
FS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
GS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     0000000000104280 00000017
IDT=     0000000000207040 00000fff
CR0=80000013 CR2=0000000000000000 CR3=0000000000107000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000001 CCD=000000003a91af5f CCO=SUBQ
EFER=0000000000000500
apic_timer_df:
 frame->ip: 0000000000100618
 frame->cs: 0000000000000008
 frame->flags: 0000000000200216
 frame->sp: 000000000020dfa8
 frame->ss: 10
 apic_timer_df_counter =1
 apic_timer_isr_counter=0
 apic_timer_loops=17373857
 lvtu.raw=0x50
 lvtu.fields.vector=80
 lvtu.fields.status=0
 lvtu.fields.disable=0
 lvtu.fields.mode=0
test_apic_timer: cli apic_timer_initial_count=0
  apic_timer_df_counter =1
  apic_timer_isr_counter=0
  apic_timer_loops=1000000000
  lvtu3.raw=0x50
  lvtu3.fields.vector=80
  lvtu3fields.status=0
  lvtu3.fields.disable=0
  lvtu3.fields.mode=0
ERROR: expr 'apic_timer_isr_counter >= 2' failed in ../arch/x86/libs/apic_x86/tests/srcs/test.c:198 FN test_apic_timer
     1: v=03 e=0000 i=1 cpl=0 IP=0008:00000000001016fa pc=00000000001016fa SP=0010:000000000020dfe0 env->regs[R_EAX]=0000000000000000
RAX=0000000000000000 RBX=0000000000000800 RCX=0000000000000000 RDX=00000000000003f8
RSI=0000000000000000 RDI=000000000000000a RBP=0000000000000000 RSP=000000000020dfe0
R8 =000000000000000a R9 =0000000000000064 R10=0000000000000000 R11=000000000000001b
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=00000000001016fa RFL=00200046 [---Z-P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
DS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
FS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
GS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     0000000000104280 00000017
IDT=     0000000000000000 00000000
CR0=80000013 CR2=0000000000000000 CR3=0000000000107000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000008 CCD=00000000fee10b01 CCO=CLR
EFER=0000000000000500
check_exception old: 0xffffffff new 0xd
     2: v=0d e=0032 i=0 cpl=0 IP=0008:00000000001016fa pc=00000000001016fa SP=0010:000000000020dfe0 env->regs[R_EAX]=0000000000000000
RAX=0000000000000000 RBX=0000000000000800 RCX=0000000000000000 RDX=00000000000003f8
RSI=0000000000000000 RDI=000000000000000a RBP=0000000000000000 RSP=000000000020dfe0
R8 =000000000000000a R9 =0000000000000064 R10=0000000000000000 R11=000000000000001b
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=00000000001016fa RFL=00200046 [---Z-P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
DS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
FS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
GS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     0000000000104280 00000017
IDT=     0000000000000000 00000000
CR0=80000013 CR2=0000000000000000 CR3=0000000000107000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000008 CCD=00000000fee10b01 CCO=CLR
EFER=0000000000000500
check_exception old: 0xd new 0xd
     3: v=08 e=0000 i=0 cpl=0 IP=0008:00000000001016fa pc=00000000001016fa SP=0010:000000000020dfe0 env->regs[R_EAX]=0000000000000000
RAX=0000000000000000 RBX=0000000000000800 RCX=0000000000000000 RDX=00000000000003f8
RSI=0000000000000000 RDI=000000000000000a RBP=0000000000000000 RSP=000000000020dfe0
R8 =000000000000000a R9 =0000000000000064 R10=0000000000000000 R11=000000000000001b
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=00000000001016fa RFL=00200046 [---Z-P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
DS =0010 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
FS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
GS =0018 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     0000000000104280 00000017
IDT=     0000000000000000 00000000
CR0=80000013 CR2=0000000000000000 CR3=0000000000107000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000008 CCD=00000000fee10b01 CCO=CLR
EFER=0000000000000500
check_exception old: 0x8 new 0xd
FAILED: '/usr/bin/python3' '/home/wink/foss/meson/meson' '--internal' 'commandrunner' '/home/wink/prgs/sadie' '/home/wink/prgs/sadie/build-pc_x86_64' 'arch/x86/libs/apic_x86/tests' '/home/wink/prgs/sadie/tools/qemu-system-x86_64.runner.sh' '/home/wink/prgs/sadie/build-pc_x86_64/arch/x86/libs/apic_x86/tests/test_apic_x86.img' '-d' 'int'