Change apic_timer_initial_count to 0 so no apic_timer_isr is generated.
Doing this we still get a double fault interrupt via apic_timer_df but
not apic_timer_isr. On the B85M-E45 test hardware we see the df firing
after some time:

  Booting `test_apic_x86'

ac_init addr=0000000000102440
mb_info: 0x0000000000222f10
 total_size=2008
 reserved=0x0
 mb_end=0x00000000002236e8
type=1 size=22
 cmd_line=test_apic_x86
type=2 size=24
type=6 size=520
 memory map:
  entry_size=24
  entry_version=0
  0: base_addr=0x0000000000000000 length=0x9ec00 type=1 reserved=96a079db
  1: base_addr=0x000000000009ec00 length=0x1400 type=2 reserved=a3ea8a20
  2: base_addr=0x00000000000e0000 length=0x20000 type=2 reserved=25dd0c97
  3: base_addr=0x0000000000100000 length=0xc6ada000 type=1 reserved=1366cd91
  4: base_addr=0x00000000c6bda000 length=0x7000 type=4 reserved=5062dc01
  5: base_addr=0x00000000c6be1000 length=0x443000 type=1 reserved=efa84a81
  6: base_addr=0x00000000c7024000 length=0x591000 type=2 reserved=cb2fb0f1
  7: base_addr=0x00000000c75b5000 length=0x117f6000 type=1 reserved=ba0c366f
  8: base_addr=0x00000000d8dab000 length=0x98000 type=2 reserved=215bce20
  9: base_addr=0x00000000d8e43000 length=0x50000 type=1 reserved=8a20d8b4
  10: base_addr=0x00000000d8e93000 length=0x135000 type=4 reserved=983e7745
  11: base_addr=0x00000000d8fc8000 length=0x1037000 type=2 reserved=2168e759
  12: base_addr=0x00000000d9fff000 length=0x1000 type=1 reserved=dd85f4c
  13: base_addr=0x00000000db000000 length=0x4200000 type=2 reserved=4f4fa034
  14: base_addr=0x00000000f8000000 length=0x4000000 type=2 reserved=3289ddf2
  15: base_addr=0x00000000fec00000 length=0x1000 type=2 reserved=fe6e85b0
  16: base_addr=0x00000000fed00000 length=0x4000 type=2 reserved=1f578bf2
  17: base_addr=0x00000000fed1c000 length=0x4000 type=2 reserved=c934c934
  18: base_addr=0x00000000fee00000 length=0x1000 type=2 reserved=c13fa227
  19: base_addr=0x00000000ff000000 length=0x1000000 type=2 reserved=325c325c
  20: base_addr=0x0000000100000000 length=0x1ee00000 type=1 reserved=594e594e
total_length=4150275072(0xf7602c00)
init_page_tables:+
RAM: base_addr=0x0 length=0x9ec00 type=1 reserved=96a079db
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=158
RAM: base_addr=0x100000 length=0xc6ada000 type=1 reserved=1366cd91
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=2, 2m=564 4k=730
RAM: base_addr=0xc6be1000 length=0x443000 type=1 reserved=efa84a81
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=2 4k=67
RAM: base_addr=0xc75b5000 length=0x117f6000 type=1 reserved=ba0c366f
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=139 4k=502
RAM: base_addr=0xd8e43000 length=0x50000 type=1 reserved=8a20d8b4
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=80
RAM: base_addr=0xd9fff000 length=0x1000 type=1 reserved=dd85f4c
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=1
RAM: base_addr=0x100000000 length=0x1ee00000 type=1 reserved=594e594e
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=247 4k=0
RAM: total_length=4150275072(0xf7602c00)
CR3 is now 0x209000
init_page_tables:- Changed to our page tables, CR3=0x107000
type=9 size=1300
type=4 size=16
 basic memory info:
  mem_lower=635k
  mem_upper=3255144k
type=5 size=20
type=8 size=32
type=15 size=44
APIC present
page_table_map_lin_to_phy:- page_table_base=0x107000 1g=0, 2m=0 4k=1
msr_apic_base 0x1b: 0xfee00900
 reserved_0=0
 bsp=1
 reserved_1=0
 extd=0
 e=1
 base=0xfee00000
 phy_addr=0xfee00000
 lin_addr=0xfee00000
 local_id=0x0
test_apic_version
msr_apic_base 0x1b: 0xfee00900
 reserved_0=0
 bsp=1
 reserved_1=0
 extd=0
 e=1
 base=0xfee00000
ver_reg=0x00000000fee00030
*ver_reg=0x1060015
test_apic_timer
test_apic_timer: lvtu.raw=0x10000
test_apic_timer: lvtu.fields.vector=0
test_apic_timer: lvtu.fields.status=0
test_apic_timer: lvtu.fields.disable=1
test_apic_timer: lvtu.fields.mode=0
test_apic_timer: lvtu2.raw=0x50
test_apic_timer: lvtu2.fields.vector=80
test_apic_timer: lvtu2fields.status=0
test_apic_timer: lvtu2.fields.disable=0
test_apic_timer: lvtu2.fields.mode=0
test_apic_timer: sti divisor=6 apic_timer_initial_count=0
apic_timer_df:
 frame->ip: 0000000000100607
 frame->cs: 0000000000000008
 frame->flags: 0000000000200297
 frame->sp: 000000000020dfa8
 frame->ss: 10
 apic_timer_df_counter =1
 apic_timer_isr_counter=0
 apic_timer_loops=6113916
 lvtu.raw=0x50
 lvtu.fields.vector=80
 lvtu.fields.status=0
 lvtu.fields.disable=0
 lvtu.fields.mode=0
test_apic_timer: cli apic_timer_initial_count=0
  apic_timer_df_counter =1
  apic_timer_isr_counter=0
  apic_timer_loops=1000000000
  lvtu3.raw=0x50
  lvtu3.fields.vector=80
  lvtu3fields.status=0
  lvtu3.fields.disable=0
  lvtu3.fields.mode=0
ERROR: expr 'apic_timer_isr_counter >= 2' failed in ../arch/x86/libs/apic_x86/tests/srcs/test.c:198 FN test_apic_timer